export const BUTTON_CLICK_REQUEST = 'BUTTON_CLICK_REQUEST'
export const BUTTON_CLICK_SUCCESS = 'BUTTON_CLICK_SUCCESS'
export const BUTTON_CLICK_FAIL = 'BUTTON_CLICK_FAIL'

export const CLICK_COUNT_REQUEST = 'CLICK_COUNT_REQUEST'
export const CLICK_COUNT_SUCCESS = 'CLICK_COUNT_SUCCESS'
export const CLICK_COUNT_FAIL = 'CLICK_COUNT_FAIL'