export const CLIENT_LOGIN_REQUEST = 'CLIENT_LOGIN_REQUEST'
export const CLIENT_LOGIN_SUCCESS = 'CLIENT_LOGIN_SUCCESS'
export const CLIENT_LOGIN_FAILURE = 'CLIENT_LOGIN_FAILURE'
export const CLIENT_LOGOUT = 'CLIENT_LOGOUT'

export const CLIENT_REGISTER_REQUEST = 'CLIENT_REGISTER_REQUEST'
export const CLIENT_REGISTER_SUCCESS = 'CLIENT_REGISTER_SUCCESS'
export const CLIENT_REGISTER_FAILURE = 'CLIENT_REGISTER_FAILURE'

export const CLIENT_DETAILS_REQUEST = 'CLIENT_DETAILS_REQUEST'
export const CLIENT_DETAILS_SUCCESS = 'CLIENT_DETAILS_SUCCESS'
export const CLIENT_DETAILS_FAILURE = 'CLIENT_DETAILS_FAILURE'
