export const CLIENT_LOGIN_REQUEST = 'CLIENT_LOGIN_REQUEST'
export const CLIENT_LOGIN_SUCCESS = 'CLIENT_LOGIN_SUCCESS'
export const CLIENT_LOGIN_FAILURE = 'CLIENT_LOGIN_FAILURE'
export const CLIENT_LOGOUT = 'CLIENT_LOGOUT'