export const MARKETER_REGISTER_REQUEST = 'MARKETER_REGISTER_REQUEST'
export const MARKETER_REGISTER_SUCCESS = 'MARKETER_REGISTER_SUCCESS'
export const MARKETER_REGISTER_FAILURE = 'MARKETER_REGISTER_FAILURE'

export const MARKETER_LOGIN_REQUEST = 'MARKETER_LOGIN_REQUEST'
export const MARKETER_LOGIN_SUCCESS = 'MARKETER_LOGIN_SUCCESS'
export const MARKETER_LOGIN_FAILURE = 'MARKETER_LOGIN_FAILURE'
export const MARKETER_LOGOUT = 'MARKETER_LOGOUT'