export const MARKETER_REGISTER_REQUEST = 'MARKETER_REGISTER_REQUEST'
export const MARKETER_REGISTER_SUCCESS = 'MARKETER_REGISTER_SUCCESS'
export const MARKETER_REGISTER_FAILURE = 'MARKETER_REGISTER_FAILURE'

export const MARKETER_LOGIN_REQUEST = 'MARKETER_LOGIN_REQUEST'
export const MARKETER_LOGIN_SUCCESS = 'MARKETER_LOGIN_SUCCESS'
export const MARKETER_LOGIN_FAILURE = 'MARKETER_LOGIN_FAILURE'
export const MARKETER_LOGOUT = 'MARKETER_LOGOUT'

export const MARKETER_DETAILS_REQUEST = 'MARKETER_DETAILS_REQUEST'
export const MARKETER_DETAILS_SUCCESS = 'MARKETER_DETAILS_SUCCESS'
export const MARKETER_DETAILS_FAILURE = 'MARKETER_DETAILS_FAILURE'