export const PRODUCT_UPLOAD_REQUEST = 'PRODUCT_UPLOAD_REQUEST'
export const PRODUCT_UPLOAD_SUCCESS = 'PRODUCT_UPLOAD_SUCCESS'
export const PRODUCT_UPLOAD_FAILURE = 'PRODUCT_UPLOAD_FAILURE'

export const USER_PRODUCT_LIST_REQUEST = 'USER_PRODUCT_LIST_REQUEST'
export const USER_PRODUCT_LIST_SUCCESS = 'USER_PRODUCT_LIST_SUCCESS'
export const USER_PRODUCT_LIST_FAILURE = 'USER_PRODUCT_LIST_FAILURE'

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAILURE = 'PRODUCT_LIST_FAILURE'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAILURE = 'PRODUCT_DELETE_FAILURE'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAILURE = 'PRODUCT_DETAILS_FAILURE'

export const PRODUCT_EDIT_REQUEST = 'PRODUCT_EDIT_REQUEST'
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS'
export const PRODUCT_EDIT_FAILURE = 'PRODUCT_EDIT_FAILURE'